" Name:         Dark Luma
" Description:  Dark, minimalist scheme with high contrast and balanced brightness
" Author:       David Golden <xdg@xdg.me>
" Maintainer:   David Golden <xdg@xdg.me>
" Website:      https://github.com/xdg/vim-darkluma
" License:      MIT
" Last Updated: Mon Oct 21 19:14:11 2019

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'darkluma'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#ff4d6a', '#22cc00', '#ccaa00',
        \ '#6680ff', '#dd33ff', '#00ccaa', '#cccccc', '#404040', '#ff99aa',
        \ '#28f000', '#e6bf00', '#a3b3ff', '#ea80ff', '#00febb', '#ffffff']
  if has('nvim')
    let g:terminal_color_0 = '#000000'
    let g:terminal_color_1 = '#ff4d6a'
    let g:terminal_color_2 = '#22cc00'
    let g:terminal_color_3 = '#ccaa00'
    let g:terminal_color_4 = '#6680ff'
    let g:terminal_color_5 = '#dd33ff'
    let g:terminal_color_6 = '#00ccaa'
    let g:terminal_color_7 = '#cccccc'
    let g:terminal_color_8 = '#404040'
    let g:terminal_color_9 = '#ff99aa'
    let g:terminal_color_10 = '#28f000'
    let g:terminal_color_11 = '#e6bf00'
    let g:terminal_color_12 = '#a3b3ff'
    let g:terminal_color_13 = '#ea80ff'
    let g:terminal_color_14 = '#00febb'
    let g:terminal_color_15 = '#ffffff'
  endif
  hi ColorColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#cccccc guibg=#000000 guisp=NONE gui=reverse cterm=reverse
  hi CursorColumn guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#22cc00 guibg=#000000 guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#ccaa00 guibg=#000000 guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#ff4d6a guibg=#000000 guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#ccaa00 guibg=#000000 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#6680ff guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#404040 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ff4d6a guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#cccccc guibg=#404040 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#cccccc guibg=#116600 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#404040 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ccaa00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#404040 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#404040 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Normal guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#cccccc guibg=#665500 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#cccccc guibg=#665500 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ccaa00 guibg=#404040 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#cccccc guibg=#665500 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=fg guibg=#665500 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#665500 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#ff4d6a guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#cccccc guibg=#000000 guisp=#ff4d6a gui=undercurl cterm=undercurl
  hi SpellCap guifg=#cccccc guibg=#000000 guisp=#6680ff gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#cccccc guibg=#000000 guisp=#dd33ff gui=undercurl cterm=undercurl
  hi SpellRare guifg=#cccccc guibg=#000000 guisp=#00ccaa gui=reverse,undercurl cterm=reverse,undercurl
  hi StatusLine guifg=#cccccc guibg=#001a99 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#cccccc guibg=#404040 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#cccccc guibg=#000000 guisp=NONE gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#404040 guibg=#404040 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#404040 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#404040 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#cccccc guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#00ccaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#cccccc guibg=#000000 guisp=NONE gui=reverse cterm=reverse
  hi Identifier guifg=#cccccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#cccccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#6680ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#00ccaa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#dd33ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#dd33ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#cccccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ff99aa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#22cc00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#00ccaa guibg=NONE guisp=#00ccaa gui=undercurl cterm=undercurl
  if get(g:, 'darkluma_dark_comments', 0)
    hi Comment guifg=#404040 guibg=NONE guisp=NONE gui=italic cterm=italic
    if !s:italics
      hi Comment gui=NONE cterm=NONE
    endif
  else
    hi Comment guifg=#ff4d6a guibg=NONE guisp=NONE gui=italic cterm=italic
    if !s:italics
      hi Comment gui=NONE cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=252 ctermbg=16 cterm=reverse
  hi CursorColumn ctermfg=252 ctermbg=16 cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi CursorLineNr ctermfg=252 ctermbg=16 cterm=NONE
  hi DiffAdd ctermfg=40 ctermbg=16 cterm=reverse
  hi DiffChange ctermfg=178 ctermbg=16 cterm=reverse
  hi DiffDelete ctermfg=197 ctermbg=16 cterm=reverse
  hi DiffText ctermfg=178 ctermbg=16 cterm=bold,reverse
  hi Directory ctermfg=69 ctermbg=16 cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=16 cterm=NONE
  hi ErrorMsg ctermfg=197 ctermbg=16 cterm=NONE
  hi FoldColumn ctermfg=252 ctermbg=16 cterm=NONE
  hi Folded ctermfg=252 ctermbg=238 cterm=NONE
  hi IncSearch ctermfg=252 ctermbg=22 cterm=NONE
  hi LineNr ctermfg=238 ctermbg=16 cterm=NONE
  hi MatchParen ctermfg=178 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=238 ctermbg=16 cterm=NONE
  hi MoreMsg ctermfg=252 ctermbg=16 cterm=NONE
  hi NonText ctermfg=238 ctermbg=16 cterm=NONE
  hi Normal ctermfg=252 ctermbg=16 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  hi Pmenu ctermfg=252 ctermbg=58 cterm=NONE
  hi PmenuSbar ctermfg=252 ctermbg=58 cterm=NONE
  hi PmenuSel ctermfg=178 ctermbg=238 cterm=NONE
  hi PmenuThumb ctermfg=252 ctermbg=58 cterm=NONE
  hi Question ctermfg=252 ctermbg=16 cterm=NONE
  hi QuickFixLine ctermfg=fg ctermbg=58 cterm=NONE
  hi Search ctermfg=NONE ctermbg=58 cterm=NONE
  hi SignColumn ctermfg=252 ctermbg=16 cterm=NONE
  hi SpecialKey ctermfg=197 ctermbg=16 cterm=NONE
  hi SpellBad ctermfg=252 ctermbg=16 cterm=underline
  hi SpellCap ctermfg=252 ctermbg=16 cterm=underline
  hi SpellLocal ctermfg=252 ctermbg=16 cterm=underline
  hi SpellRare ctermfg=252 ctermbg=16 cterm=reverse,underline
  hi StatusLine ctermfg=252 ctermbg=19 cterm=NONE
  hi StatusLineNC ctermfg=252 ctermbg=238 cterm=NONE
  hi TabLine ctermfg=252 ctermbg=16 cterm=NONE
  hi TabLineFill ctermfg=252 ctermbg=16 cterm=NONE
  hi TabLineSel ctermfg=252 ctermbg=16 cterm=NONE
  hi Title ctermfg=252 ctermbg=16 cterm=NONE
  hi ToolbarButton ctermfg=252 ctermbg=16 cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=16 cterm=NONE
  hi VertSplit ctermfg=238 ctermbg=238 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=238 cterm=NONE
  hi WarningMsg ctermfg=252 ctermbg=16 cterm=NONE
  hi WildMenu ctermfg=252 ctermbg=16 cterm=NONE
  hi Constant ctermfg=43 ctermbg=NONE cterm=NONE
  hi Error ctermfg=252 ctermbg=16 cterm=reverse
  hi Identifier ctermfg=252 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=252 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=69 ctermbg=NONE cterm=NONE
  hi Label ctermfg=43 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=165 ctermbg=NONE cterm=NONE
  hi Special ctermfg=165 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=252 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=211 ctermbg=NONE cterm=NONE
  hi Type ctermfg=40 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=43 ctermbg=NONE cterm=underline
  if get(g:, 'darkluma_dark_comments', 0)
    hi Comment ctermfg=238 ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  else
    hi Comment ctermfg=197 ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 16
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi CursorColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=Black cterm=reverse
  hi DiffText ctermfg=DarkYellow ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=DarkBlue ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi FoldColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi IncSearch ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi NonText ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=DarkYellow ctermbg=DarkGrey cterm=NONE
  hi PmenuThumb ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi QuickFixLine ctermfg=fg ctermbg=Black cterm=NONE
  hi Search ctermfg=NONE ctermbg=Black cterm=NONE
  hi SignColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=LightGrey ctermbg=Black cterm=underline
  hi SpellCap ctermfg=LightGrey ctermbg=Black cterm=underline
  hi SpellLocal ctermfg=LightGrey ctermbg=Black cterm=underline
  hi SpellRare ctermfg=LightGrey ctermbg=Black cterm=reverse,underline
  hi StatusLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi WarningMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Constant ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Error ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi Identifier ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Type ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=DarkCyan ctermbg=NONE cterm=underline
  if get(g:, 'darkluma_dark_comments', 0)
    hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  else
    hi Comment ctermfg=DarkRed ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         rgb(  0,   0,   0)        ~         Black
" Color: red           rgb(255,  77, 106)        ~         DarkRed
" Color: green         rgb( 34, 204,   0)        ~         DarkGreen
" Color: yellow        rgb(204, 170,   0)        ~         DarkYellow
" Color: blue          rgb(102, 128, 255)        ~         DarkBlue
" Color: magenta       rgb(221,  51, 255)        ~         DarkMagenta
" Color: cyan          rgb(  0, 204, 170)        ~         DarkCyan
" Color: white         rgb(204, 204, 204)        ~         LightGrey
" Color: gray          rgb( 64,  64,  64)        ~         DarkGrey
" Color: brightred     rgb(255, 153, 170)        ~         LightRed
" Color: brightgreen   rgb( 40, 240,   0)        ~         LightGreen
" Color: brightyellow  rgb(230, 191,   0)        ~         LightYellow
" Color: brightblue    rgb(163, 179, 255)        ~         LightBlue
" Color: brightmagenta rgb(234, 128, 255)        ~         LightMagenta
" Color: brightcyan    rgb(  0, 254, 187)        ~         LightCyan
" Color: brightwhite   rgb(255, 255, 255)        ~         White
" Color: black90pct    rgb( 25,  25,  25)        ~         Black
" Color: darkgold      rgb(102,  85,   0)        ~         Black
" Color: darkgreen     rgb( 17, 102,   0)        ~         Black
" Color: darkblue      rgb(  0,  26, 153)        ~         Black
" Term colors: black red green yellow blue magenta cyan white
" Term colors: gray brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
