" Name:         Dark Luma
" Description:  Dark, minimalist scheme with high contrast and balanced brightness
" Author:       David Golden <xdg@xdg.me>
" Maintainer:   David Golden <xdg@xdg.me>
" Website:      https://github.com/xdg/vim-darkluma
" License:      MIT
" Last Change:  2025 Apr 23

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'darkluma'

let s:t_Co = has('gui_running') ? -1 : get(g:, 'darkluma_t_Co', get(g:, 't_Co', exists('&t_Co') ? +&t_Co : 0))
let s:italics = has('gui_running') || has('nvim') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

hi! link Whitespace NonText
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor
hi! link goPackage Statement
hi! link goImport Statement
hi! link goConst Statement
hi! link goDeclaration Keyword
hi! link goDeclType Type
hi! link goVar Statement
hi! link goStatement Statement
hi! link goConditional Statement
hi! link goLabel Statement
hi! link goRepeat Statement
hi! link goBuiltins Statement

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#262626', '#e04660', '#139b00', '#ccaa00', '#6680ff', '#af0dec', '#3aada5', '#cccccc', '#7f7f7f', '#ff99aa', '#28f000', '#e6bf00', '#a3b3ff', '#ea80ff', '#00febb', '#ffffff']
endif
if has('nvim')
  let g:terminal_color_0 = '#262626'
  let g:terminal_color_1 = '#e04660'
  let g:terminal_color_2 = '#139b00'
  let g:terminal_color_3 = '#ccaa00'
  let g:terminal_color_4 = '#6680ff'
  let g:terminal_color_5 = '#af0dec'
  let g:terminal_color_6 = '#3aada5'
  let g:terminal_color_7 = '#cccccc'
  let g:terminal_color_8 = '#7f7f7f'
  let g:terminal_color_9 = '#ff99aa'
  let g:terminal_color_10 = '#28f000'
  let g:terminal_color_11 = '#e6bf00'
  let g:terminal_color_12 = '#a3b3ff'
  let g:terminal_color_13 = '#ea80ff'
  let g:terminal_color_14 = '#00febb'
  let g:terminal_color_15 = '#ffffff'
endif
hi Normal guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi NonText guifg=#7f7f7f guibg=bg gui=NONE cterm=NONE
hi Conceal guifg=fg guibg=#262626 gui=NONE cterm=NONE
hi MatchParen guifg=#ccaa00 guibg=bg gui=NONE cterm=NONE
hi SpecialKey guifg=#e04660 guibg=bg gui=NONE cterm=NONE
hi Visual guifg=fg guibg=#7f7f7f gui=NONE cterm=NONE
hi VisualNOS guifg=fg guibg=#7f7f7f gui=NONE cterm=NONE
hi ColorColumn guifg=fg guibg=bg gui=NONE cterm=NONE
hi CursorColumn guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi EndOfBuffer guifg=#7f7f7f guibg=#191919 gui=NONE cterm=NONE
hi Cursor guifg=#cccccc guibg=#191919 gui=reverse cterm=reverse
hi CursorColumn guifg=fg guibg=#333233 gui=NONE cterm=NONE
hi CursorLine guifg=fg guibg=#333233 gui=NONE cterm=NONE
hi DiffAdd guifg=#139b00 guibg=#191919 gui=reverse cterm=reverse
hi DiffChange guifg=#ccaa00 guibg=#191919 gui=reverse cterm=reverse
hi DiffDelete guifg=#e04660 guibg=#191919 gui=reverse cterm=reverse
hi DiffText guifg=#ccaa00 guibg=#191919 gui=bold,reverse cterm=bold,reverse
hi FoldColumn guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
hi Folded guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
hi IncSearch guifg=#262626 guibg=#d6ca88 gui=bold,underline cterm=bold,underline
hi Search guifg=#262626 guibg=#ccaa00 gui=underline cterm=underline
hi Substitute guifg=#262626 guibg=#ccaa00 gui=NONE cterm=NONE
hi CursorLineNr guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi LineNr guifg=#7f7f7f guibg=#262626 gui=NONE cterm=NONE
hi SignColumn guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi ErrorMsg guifg=#e04660 guibg=#191919 gui=NONE cterm=NONE
hi WarningMsg guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi ModeMsg guifg=#7f7f7f guibg=#191919 gui=NONE cterm=NONE
hi MoreMsg guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi Question guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi StatusLine guifg=#cccccc guibg=#001a99 gui=NONE cterm=NONE
hi StatusLineNC guifg=#cccccc guibg=#7f7f7f gui=NONE cterm=NONE
hi Pmenu guifg=#cccccc guibg=#7f7f7f gui=NONE cterm=NONE
hi PmenuSbar guifg=#cccccc guibg=#7f7f7f gui=NONE cterm=NONE
hi PmenuSel guifg=#ccaa00 guibg=#191919 gui=NONE cterm=NONE
hi PmenuThumb guifg=#cccccc guibg=#665500 gui=NONE cterm=NONE
hi SpellBad guifg=#cccccc guibg=#191919 guisp=#e04660 gui=undercurl cterm=underline
hi SpellCap guifg=#cccccc guibg=#191919 guisp=#6680ff gui=undercurl cterm=underline
hi SpellLocal guifg=#cccccc guibg=#191919 guisp=#af0dec gui=undercurl cterm=underline
hi SpellRare guifg=#cccccc guibg=#191919 guisp=#3aada5 gui=reverse,undercurl cterm=reverse,underline
hi TabLine guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi TabLineFill guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi TabLineSel guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi Title guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi ToolbarButton guifg=#cccccc guibg=#191919 gui=bold cterm=bold
hi ToolbarLine guifg=fg guibg=#191919 gui=NONE cterm=NONE
hi VertSplit guifg=#7f7f7f guibg=bg gui=NONE cterm=NONE
hi WinSeparator guifg=#7f7f7f guibg=bg gui=NONE cterm=NONE
hi WildMenu guifg=#cccccc guibg=#191919 gui=NONE cterm=NONE
hi Directory guifg=#6680ff guibg=#191919 gui=NONE cterm=NONE
hi CopilotSuggestion guifg=#7f7f7f guibg=#191919 gui=NONE cterm=NONE
hi Constant guifg=#3aada5 guibg=bg gui=NONE cterm=NONE
hi Error guifg=fg guibg=#e04660 gui=NONE cterm=NONE
hi Identifier guifg=#cccccc guibg=bg gui=NONE cterm=NONE
hi Ignore guifg=#cccccc guibg=bg gui=NONE cterm=NONE
hi Keyword guifg=#6680ff guibg=bg gui=NONE cterm=NONE
hi Label guifg=#3aada5 guibg=bg gui=NONE cterm=NONE
hi PreProc guifg=#af0dec guibg=bg gui=NONE cterm=NONE
hi Special guifg=#af0dec guibg=bg gui=NONE cterm=NONE
hi Statement guifg=#cccccc guibg=bg gui=NONE cterm=NONE
hi Todo guifg=#ff99aa guibg=bg gui=NONE cterm=NONE
hi Type guifg=#139b00 guibg=bg gui=NONE cterm=NONE
hi Underlined guifg=#3aada5 guibg=bg guisp=#3aada5 gui=undercurl cterm=underline
if get(g:, 'darkluma_dark_comments', 0)
  hi Comment guifg=#7f7f7f guibg=bg gui=italic cterm=italic
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
else
  hi Comment guifg=#c07e4d guibg=bg gui=italic cterm=italic
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
endif

if s:t_Co >= 256
  hi Normal ctermfg=252 ctermbg=234 cterm=NONE
  hi NonText ctermfg=244 ctermbg=bg cterm=NONE
  hi Conceal ctermfg=fg ctermbg=235 cterm=NONE
  hi MatchParen ctermfg=178 ctermbg=bg cterm=NONE
  hi SpecialKey ctermfg=197 ctermbg=bg cterm=NONE
  hi Visual ctermfg=fg ctermbg=244 cterm=NONE
  hi VisualNOS ctermfg=fg ctermbg=244 cterm=NONE
  hi ColorColumn ctermfg=fg ctermbg=bg cterm=NONE
  hi CursorColumn ctermfg=252 ctermbg=234 cterm=NONE
  hi EndOfBuffer ctermfg=244 ctermbg=234 cterm=NONE
  hi Cursor ctermfg=252 ctermbg=234 cterm=reverse
  hi CursorColumn ctermfg=fg ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=fg ctermbg=236 cterm=NONE
  hi DiffAdd ctermfg=34 ctermbg=234 cterm=reverse
  hi DiffChange ctermfg=178 ctermbg=234 cterm=reverse
  hi DiffDelete ctermfg=197 ctermbg=234 cterm=reverse
  hi DiffText ctermfg=178 ctermbg=234 cterm=bold,reverse
  hi FoldColumn ctermfg=252 ctermbg=235 cterm=NONE
  hi Folded ctermfg=252 ctermbg=235 cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=186 cterm=bold,underline
  hi Search ctermfg=235 ctermbg=178 cterm=underline
  hi Substitute ctermfg=235 ctermbg=178 cterm=NONE
  hi CursorLineNr ctermfg=252 ctermbg=234 cterm=NONE
  hi LineNr ctermfg=244 ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=252 ctermbg=234 cterm=NONE
  hi ErrorMsg ctermfg=197 ctermbg=234 cterm=NONE
  hi WarningMsg ctermfg=252 ctermbg=234 cterm=NONE
  hi ModeMsg ctermfg=244 ctermbg=234 cterm=NONE
  hi MoreMsg ctermfg=252 ctermbg=234 cterm=NONE
  hi Question ctermfg=252 ctermbg=234 cterm=NONE
  hi StatusLine ctermfg=252 ctermbg=19 cterm=NONE
  hi StatusLineNC ctermfg=252 ctermbg=244 cterm=NONE
  hi Pmenu ctermfg=252 ctermbg=244 cterm=NONE
  hi PmenuSbar ctermfg=252 ctermbg=244 cterm=NONE
  hi PmenuSel ctermfg=178 ctermbg=234 cterm=NONE
  hi PmenuThumb ctermfg=252 ctermbg=58 cterm=NONE
  hi SpellBad ctermfg=252 ctermbg=234 cterm=underline
  hi SpellCap ctermfg=252 ctermbg=234 cterm=underline
  hi SpellLocal ctermfg=252 ctermbg=234 cterm=underline
  hi SpellRare ctermfg=252 ctermbg=234 cterm=reverse,underline
  hi TabLine ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineFill ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineSel ctermfg=252 ctermbg=234 cterm=NONE
  hi Title ctermfg=252 ctermbg=234 cterm=NONE
  hi ToolbarButton ctermfg=252 ctermbg=234 cterm=bold
  hi ToolbarLine ctermfg=fg ctermbg=234 cterm=NONE
  hi VertSplit ctermfg=244 ctermbg=bg cterm=NONE
  hi WinSeparator ctermfg=244 ctermbg=bg cterm=NONE
  hi WildMenu ctermfg=252 ctermbg=234 cterm=NONE
  hi Directory ctermfg=69 ctermbg=234 cterm=NONE
  hi CopilotSuggestion ctermfg=244 ctermbg=234 cterm=NONE
  hi Constant ctermfg=37 ctermbg=bg cterm=NONE
  hi Error ctermfg=fg ctermbg=197 cterm=NONE
  hi Identifier ctermfg=252 ctermbg=bg cterm=NONE
  hi Ignore ctermfg=252 ctermbg=bg cterm=NONE
  hi Keyword ctermfg=69 ctermbg=bg cterm=NONE
  hi Label ctermfg=37 ctermbg=bg cterm=NONE
  hi PreProc ctermfg=129 ctermbg=bg cterm=NONE
  hi Special ctermfg=129 ctermbg=bg cterm=NONE
  hi Statement ctermfg=252 ctermbg=bg cterm=NONE
  hi Todo ctermfg=211 ctermbg=bg cterm=NONE
  hi Type ctermfg=34 ctermbg=bg cterm=NONE
  hi Underlined ctermfg=37 ctermbg=bg cterm=underline
  if get(g:, 'darkluma_dark_comments', 0)
    hi Comment ctermfg=244 ctermbg=bg cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  else
    hi Comment ctermfg=173 ctermbg=bg cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal cterm=NONE
  hi ColorColumn cterm=reverse
  hi Conceal cterm=NONE
  hi Cursor cterm=NONE
  hi CursorColumn cterm=reverse
  hi CursorLine cterm=underline
  hi CursorLineNr cterm=bold,italic,reverse,underline
  hi DiffAdd cterm=reverse,underline
  hi DiffChange cterm=reverse,underline
  hi DiffDelete cterm=reverse,underline
  hi DiffText cterm=bold,reverse,underline
  hi Directory cterm=NONE
  hi EndOfBuffer cterm=NONE
  hi ErrorMsg cterm=bold,italic,reverse
  hi FoldColumn cterm=reverse
  hi Folded cterm=italic,reverse,underline
  hi IncSearch cterm=bold,italic,reverse
  hi LineNr cterm=reverse
  hi MatchParen cterm=bold,underline
  hi ModeMsg cterm=NONE
  hi MoreMsg cterm=NONE
  hi NonText cterm=NONE
  hi Pmenu cterm=reverse
  hi PmenuSbar cterm=NONE
  hi PmenuSel cterm=NONE
  hi PmenuThumb cterm=NONE
  hi Question cterm=standout
  hi Search cterm=italic,underline
  hi SignColumn cterm=reverse
  hi SpecialKey cterm=bold
  hi SpellBad cterm=italic,underline
  hi SpellCap cterm=italic,underline
  hi SpellLocal cterm=italic,underline
  hi SpellRare cterm=italic,underline
  hi StatusLine cterm=bold,reverse
  hi StatusLineNC cterm=reverse
  hi TabLine cterm=italic,reverse,underline
  hi TabLineFill cterm=reverse,underline
  hi TabLineSel cterm=bold
  hi Title cterm=bold
  hi VertSplit cterm=reverse
  hi Visual cterm=reverse
  hi VisualNOS cterm=NONE
  hi WarningMsg cterm=standout
  hi WildMenu cterm=bold
  hi Comment cterm=italic
  hi Constant cterm=bold,italic
  hi Error cterm=reverse
  hi Identifier cterm=italic
  hi Ignore cterm=NONE
  hi PreProc cterm=italic
  hi Special cterm=bold,italic
  hi Statement cterm=bold
  hi Todo cterm=bold,underline
  hi Type cterm=bold
  hi Underlined cterm=underline
  hi CursorIM cterm=NONE
  hi ToolbarLine cterm=reverse
  hi ToolbarButton cterm=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         rgb( 38,  38,  38)        ~
" Color: red           rgb(224,  70,  96)        ~
" Color: orange        rgb(192, 126,  77)        ~
" Color: green         rgb( 19, 155,   0)        ~
" Color: yellow        rgb(204, 170,   0)        ~
" Color: blue          rgb(102, 128, 255)        ~
" Color: magenta       rgb(175,  13, 236)        ~
" Color: cyan          rgb( 58, 173, 165)        ~
" Color: white         rgb(204, 204, 204)        ~
" Color: gray          rgb(127, 127, 127)        ~
" Color: brightred     rgb(255, 153, 170)        ~
" Color: brightgreen   rgb( 40, 240,   0)        ~
" Color: brightyellow  rgb(230, 191,   0)        ~
" Color: brightblue    rgb(163, 179, 255)        ~
" Color: brightmagenta rgb(234, 128, 255)        ~
" Color: brightcyan    rgb(  0, 254, 187)        ~
" Color: brightwhite   rgb(255, 255, 255)        ~
" Color: black80pct    rgb( 51,  50,  51)        ~
" Color: black85pct    rgb( 38,  38,  38)        ~
" Color: black90pct    rgb( 25,  25,  25)        ~
" Color: darkgold      rgb(102,  85,   0)        ~
" Color: darkgreen     rgb( 17, 102,   0)        ~
" Color: darkblue      rgb(  0,  26, 153)        ~
" Color: highyellow    rgb(214, 202, 136)        ~
" Term colors: black red green yellow blue magenta cyan white
" Term colors: gray brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
